project_id = "kgnnhstwjefvormjdvna"

[functions.ai-apurador]
verify_jwt = false

[functions.ai-campaign-consultant]
verify_jwt = false

[functions.ai-column-mapper]
verify_jwt = false

[functions.ai-data-analyzer]
verify_jwt = false

[functions.ai-rule-processor]
verify_jwt = false

[functions.process-campaign-file]
verify_jwt = false