-- Disable Row Level Security on all tables
ALTER TABLE public.campaign_files DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.credits DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.dispatch_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.partial_calculations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.participants DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rankings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rule_raw DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rule_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_data DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.upload_logs DISABLE ROW LEVEL SECURITY;