// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgnnhstwjefvormjdvna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtnbm5oc3R3amVmdm9ybWpkdm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNDk4MzIsImV4cCI6MjA3NTYyNTgzMn0.Mr9qAGw9zc4wdMu8H5FeOhAjm-s11S1Mj0TM0fcSzVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});